name: generate animation

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
      - master
    
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: qkrxogmla
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=custom
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          SNAKE_PALETTE_CUSTOM: |
            {
              "background": "#fffafd",
              "grid": "#ffe5e5",
              "snake": "#ffa3a3",
              "stages": [
                "#dbe2ff", # 기여도 낮음
                "#a3d3ff", # 기여도 중간
                "#1e293b"  # 기여도 높음
              ]
            }

      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
